name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Project_Name: Hydra.csproj  # Replace with your project file name

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore the application
        run: dotnet restore $env:Project_Name

      - name: Build the application
        run: dotnet build $env:Project_Name --configuration ${{ matrix.configuration }} --no-restore

      - name: Execute unit tests
        run: dotnet test $env:Project_Name --no-restore --verbosity normal

      - name: Publish the application
        run: dotnet publish $env:Project_Name --configuration ${{ matrix.configuration }} --no-restore --output publish/
      
      # Additional steps for packaging, signing, and artifact uploading can go here.
      # If your project does not require these steps, you can remove them or comment them out.
      
      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Published Application
          path: publish/
